/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tanvi
 */

import java.sql.*;
import ebs.connectionProvider;
import java.awt.Font;
import javax.swing.JOptionPane;


public class GenerateReceipt extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReceipt
     */
    Connection con;
    Statement stmt;
    
    public GenerateReceipt() {
        initComponents();
    }
    public GenerateReceipt(String user,String name,String ucity,String ucontact,String uemail, String meterid,String location,String type,String days){
        initComponents();
        try{
            con = connectionProvider.getConnection();
            stmt = con.createStatement();
            //sc = new Scanner(System.in);
        }catch(Exception e){
            e.printStackTrace();
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Could not start the application!");
            //this.dispose();        }
        }
        jComboBox1.addItem("select");
        area.setFont(new Font("Senserif", Font.ITALIC, 18));
        setDetails(user,name,ucity,ucontact,uemail,meterid,location,type,days);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void setDetails(String user,String name,String ucity,String ucontact,String uemail, String meterid,String location,String type,String days)
    {
        String query = "SELECT * FROM bills WHERE userName = '"+user+"' AND paid = true;";
        String entry;
        //String [] data = new String[30];
        //int i;
        try{
            ResultSet rs = stmt.executeQuery(query);
            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null,"You have no paid bills!!");
                setVisible(false);
                
            }else{
                //i = 0;
                
                do
                {
                    entry = Integer.toString(rs.getInt("billid")) + " (" + rs.getString("month") + " " + rs.getString("year") + ")" ;
                    //data[i] = entry;
                    jComboBox1.addItem(entry);
                }while(rs.next());
                
            }
            area.setText("\n                ELECTRICITY BILL                   \n");
            area.append("\n---------------------------------------------------\n\n");
            area.append("\n    Customer Name        : "+name+"");
            area.append("\n    Contact              : "+ucontact+"");
            area.append("\n    City                 : "+ucity+"");
            area.append("\n    Email                : "+uemail+"");
            area.append("\n---------------------------------------------------\n\n");
            area.append("\n    Meter Id             : "+meterid+"");
            area.append("\n    Location             : "+location+"");
            area.append("\n    Meter Type           : "+type+"");
            area.append("\n    Bill Cycle           : "+days+"");
            area.append("\n---------------------------------------------------\n\n");
        }catch(Exception e)
        {
            e.printStackTrace();
            System.out.println("Error occured while retreiving your bills " + e);
            JOptionPane.showMessageDialog(null,"Error occured while retreiving your bills !!");
            setVisible(false);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Receipt");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Select Bill : ");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String data = (String)jComboBox1.getSelectedItem();
        int indexSpace = data.indexOf(" ");
        if(indexSpace != -1){
            String query = "SELECT * FROM bills WHERE billid = "+data.substring(0,indexSpace)+";";
            try{
                ResultSet rs = stmt.executeQuery(query);
                if(rs.next())
                {
                    jComboBox1.setEnabled(false);
                    area.append("\n    Bill Id             : "+Integer.toString(rs.getInt("billid"))+"");
                    area.append("\n    Units Consumed      : "+Integer.toString(rs.getInt("units"))+" (KWH)");
                    area.append("\n    Amount              : "+Float.toString(rs.getFloat("amount"))+"");
                    area.append("\n    Month               : "+rs.getString("month")+"");
                    area.append("\n    Year                : "+rs.getString("year")+"");
                    area.append("\n    Generated_on        : "+rs.getTimestamp("generated_on").toString()+"");
                    area.append("\n    Paid_on             : "+rs.getTimestamp("paid_on").toString()+"");
                    area.append("\n");
                    rs.close();
                }
            }catch(Exception e){
                e.printStackTrace();
                System.out.println("Error occured while retreiving your bills " + e);
                JOptionPane.showMessageDialog(null,"Error occured while retreivinf bill data!!");
            }
            
        }
        System.out.println("Changed");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
